FROM elixir:1.4.2
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app
COPY ./elixir_words_api.tar.gz ./
RUN tar xfz elixir_words_api.tar.gz

ENTRYPOINT ["bin/elixir_words_api"]
